Added recursive restore to allow also versions of children
sulu-io/sulu-document-manager pull request #108
Opened 2017-03-22 15:57 UTC by wachterjohannes

This PR extends the `VersionSubscriber` to allow also restore children.

2017-04-18 15:14 UTC, danrot requested changes

2017-04-18 15:14 UTC, danrot commented on lib/Subscriber/Behavior/VersionSubscriber.php
> +        // remove child-nodes which does not exists in frozen-node
`which do not exist in frozen node`

2017-04-18 15:14 UTC, danrot commented on tests/Unit/Subscriber/Behavior/VersionSubscriberTest.php
> +        $node->getNodes()->willReturn([]);
Please add also a test where the node has children, which should not be copied (as it is the case with the pages).

2017-04-19 07:10 UTC, wachterjohannes commented
@danrot fixed

2017-04-19 10:12 UTC, danrot requested changes

2017-04-19 10:12 UTC, danrot commented on tests/Unit/Subscriber/Behavior/VersionSubscriberTest.php
> +        $this->versionSubscriber->restoreProperties($event->reveal());
There's not a single assertion in this test, so we cannot be sure that the child node has not been touched...

2017-04-19 10:21 UTC, wachterjohannes commented on tests/Unit/Subscriber/Behavior/VersionSubscriberTest.php
> +        $this->versionSubscriber->restoreProperties($event->reveal());
it's not explicit but we could. every not mocked method call would let this test fail - but i will add some assertions.

2017-04-19 10:26 UTC, wachterjohannes commented on tests/Unit/Subscriber/Behavior/VersionSubscriberTest.php
> +        // the child-node should not be touched
@danrot i have added assertions

2017-04-19 10:37 UTC, danrot approved these changes

2017-04-19 10:40 UTC, merged