Added metadata to configure remove-live
sulu-io/sulu-document-manager pull request #109
Opened 2017-04-11 05:57 UTC by wachterjohannes

This PR introduces a boolean flag which will be used by sulu to configure the behavior for removing instances of this document.

See #???

2017-04-11 14:16 UTC, danrot requested changes

2017-04-11 14:16 UTC, danrot commented on lib/Metadata.php
> +    private $removeLive = true;
I am somehow missing the connection that this is done automatically when the draft is deleted. Maybe `syncRemoveAcrossWorkspaces`? Although this is quite a long one... Or `syncRemoveLive`?

2017-04-11 14:16 UTC, danrot commented on lib/Metadata.php
> +    private $removeLive = true;
Not completely sure about this now, but `removeLive` could also be interpreted as never having a live node at all.

2017-04-12 14:14 UTC, wachterjohannes commented on lib/Metadata.php
> +    private $removeLive = true;
@danrot in my opinion, the `syncRemovLive` sounds good but not perfect ... but i cannot think of any other name. what should i do? (:

2017-04-12 14:47 UTC, danrot commented on lib/Metadata.php
> +    private $removeLive = true;
Let's take `syncRemoveLive`, since we don't know a better name...

2017-04-13 05:31 UTC, wachterjohannes commented on lib/Metadata.php
> +    private $removeLive = true;
@danrot fixed

2017-04-13 07:49 UTC, wachterjohannes commented
@danrot fixed

2017-04-13 09:21 UTC, danrot approved these changes

2017-04-13 09:21 UTC, merged