Added overwrite option to ExplicitSubscriber
sulu-io/sulu-document-manager pull request #96
Opened 2016-11-16 09:22 UTC by wachterjohannes

This PR introduces overwrite option to enhance the developer to overwrite a already existing node.

2016-11-16 09:38 UTC, wachterjohannes commented
@danrot can you add your thoughts about this change?

2016-11-16 10:04 UTC, danrot requested changes

2016-11-16 10:04 UTC, danrot commented on lib/Subscriber/Behavior/Path/ExplicitSubscriber.php
> +            'overwrite' => false,
Use `override`

2016-11-16 12:31 UTC, wachterjohannes commented
@danrot fixed

2016-11-17 10:51 UTC, danrot commented
Changelog missing

2016-11-17 11:02 UTC, wachterjohannes commented
@danrot fixed

2016-11-17 14:15 UTC, danrot approved these changes

2016-11-17 14:16 UTC, merged